### ISSUE TITLE
MaybeNumber's Coercion with Queries Returns Unexpected Results

### ISSUE THREAD

**Issue by indifferentghost** [canjs/can-data-types#7]
`MaybeNumber`'s coercion has unexpected results when comparing query to query.
```js
const queryLogic = new QueryLogic({
  identity: ["id"],
  keys: { age: MaybeNumber }
});
const unionized = queryLogic.union(
  {filter: {age: 7}},
  {filter: {age: "07"}}
);
console.log( unionized );
// expected:  {filter: {age: 7}}, received:  "{'filter':{'age':{'$in':[7,'07']}}}"
```
demo: https://codepen.io/TDillard/pen/MqZqzO

Similarly, `MaybeNumber` has unexpected results when comparing query to an instance.
- `queryLogic.filterMembers({filter: {age: 7}}, [{age: "07"}]);` returns `[{age: "07"}]`.
- `queryLogic.filterMembers({filter: {age: "07"}}, [{age: 7}])` returns an empty array.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-query-logic #19](https://github.com/canjs/can-query-logic/issues/19) via [**ZenHub**](https://www.zenhub.com/)
